// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enqebleurghnjctdipbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVucWVibGV1cmdobmpjdGRpcGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjI2MzAsImV4cCI6MjA2MDM5ODYzMH0.xQfCUrqjSIG7WSUeh6TN1O1twxfUgYlM1aWxvhNVXUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);